name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 2.0.3

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface: ^1.0.1
  flutter_image_compress_common:
    git:
      url: https://github.com/basveenema/flutter_image_compress
      branch: fix_oom_android_fork
      path: packages/flutter_image_compress_common
  flutter_image_compress_web: ^0.1.3

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common
      web:
        default_package: flutter_image_compress_web